### ISSUE TITLE
clone_only strategy fail - panics - not implemented

### ISSUE THREAD

**Issue by nphias** [holochain/holochain#3056]
**Describe the bug**
In the App_manifest using the provisioning strategy: clone_only
causes a panic and crash during InstallApp

**Expected behavior**
during InstallApp , should defer the role and allow the agent to clone the DNA at runtime 

**System information:**
 - OS: mac os
 - Holochain and HDK Version 0.2.3-rc.1

**Steps to reproduce**
in the app manifest happ.yaml add a role entry like this:

```
- name: mydna
    provisioning:
      strategy: clone_only
      deferred: true
    dna:
      bundled: "../dnas/mydna/workdir/mydna.dna"
      modifiers:
        network_seed: ~
        properties: ~
        origin_time: ~
        quantum_time: ~
      installed_hash: ~
      clone_limit: 1000
```
then try to run the conductor

error messages:

```
00:25:28 [Tryorama - Local Conductor] info: FATAL PANIC PanicInfo {
    payload: Any { .. },
    message: Some(
        not implemented,
    ),
    location: Location
00:25:28 [Tryorama - Local Conductor] info:  {
        file: "crates/holochain_conductor_api/src/app_interface.rs",
        line: 360,
        col: 17,
    },
    can_unwind: true,
}
```
