### ISSUE TITLE
[BUG] DNA manifest with `bundled` zomes should not allow paths with parent directories

### ISSUE THREAD

**Issue by maackle** [holochain/holochain#3294]
**Describe the bug**

Consider this DNA manifest:

```yaml
manifest_version: '1'
name: mydna
integrity:
  network_seed: null
  properties: null
  origin_time: 1669408001130688
  zomes:
  - name: myzome
    hash: null
    bundled: ../../zomes/myzome.wasm
    dependencies: null
    dylib: null
```

If I have built this as `mydna.dna`, then if I run `hc dna unpack mydna.dna`, the zome will get unpacked in the parent of the working directory. This is confusing.

**Expected behavior**

Bundled paths should not allow referencing parent directories, the paths should all be under the relative root.

**System information:**

Ubuntu
