### ISSUE TITLE
Coordinator updates: Manifest refactor

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#4404]
Design: [`docs/design/coordinator_upgrades.md`](https://github.com/holochain/holochain/blob/develop/docs/design/coordinator_upgrades.md).

Coordinators are not part of the DNA and should not be shipped inside it. Move them out of the DNA manifest and onto the app role, so a coordinator set becomes a swappable, app-owned component. This is the precondition for app-level `update_app` (#4570).

## Acceptance criteria

- The DNA manifest has no `coordinator:` block. The `integrity:` block is unchanged.
- The app role gains a flat `coordinators:` list, and `clone_limit` moves up from `dna:` to the role.
- `hash` on a zome is optional wherever it appears: verified when present, computed when absent.
- `dependencies` on a coordinator zome stays an optional list of integrity zome names, omitted when the DNA has a single integrity zome.
- `IntegrityManifest` and `CoordinatorManifest` are renamed, since neither is a manifest.
- `manifest_version` stays `"0"`. A manifest in the old layout fails to parse with an error that says what moved where.
- Bundles, fixtures, the JSON schema and the `hc` packing commands all work with the new layout.

## Resolved from the discussion below

- **Manifest version.** No bump to `"2"`, and no compatibility shim for the current layout. The format is not stable yet, which is what `"0"` says.
- **Flattening the DNA manifest** so `network_seed`/`properties`/`zomes` sit at the root: rejected. The `integrity:` block is exactly the DnaHash preimage — `DnaDefHash` is modifiers plus integrity zomes, while `name` and `lineage` sit outside it and contribute nothing. Keeping it fenced off keeps "did the DnaHash change?" legible, and that is the question `update_app` gates on.
- **The `hash` field.** Optional, as asked for in the thread. The hash that binds a capability grant to a coordinator is injected by the conductor and never appears in a manifest — see #4911.
- **Renaming `dependencies` to a singular `dependency`.** Rejected. Whether a coordinator may depend on more than one integrity zome is open (#4660, #4518). Keeping the field plural means lifting that limit later does not break the manifest a second time.
- **Renaming `roles`.** Out of scope. The terminology is too deeply embedded to change here.

**Comment by mattyg** [comment]
> Should we consider bumping the version on the manifest to 2 and continuing to accept version 1 manifests? That might ease the breaking change and there are many apps out there using manifest version 1. 

I strongly encourage this

**Comment by ThetaSinner** [comment]
I'm going to suggest that we don't introduce a new manifest version right now. We've already broken the manifest format in 0.6.

The DNA manifest should become:

```yaml
---
manifest_version: "1"
name: group
network_seed: 00000000-0000-0000-0000-000000000000
properties: ~
zomes:
  - name: group_integrity
    hash: uASDFJCaskldfjsdkalfj
    path: ../../../target/wasm32-unknown-unknown/release/group_integrity.wasm
```

Because we're separating integrity and coordinators, we can flatten the network seed and properties up to the root of the DNA manifest. The `network_seed`, `properties` and `zomes` currently live under `integrity`. That key makes no sense in this context since that is the entire content of the DNA now.

As part of this change, I recommend we rename any types like `IntegrityManifest` which do not actually implement `Manifest`. It's confusing for us and adding nothing to the end user who just sees YAML fields that don't include the Rust type names.

I also recommend that we split up the `ZomeManifest` type. The `dependencies` field for a zome is only relevant to a coordinator zome and it shouldn't be possible to set that field in an integrity manifest.

Then we need to move coordinators into the app manifest:

```yaml
roles:
  - name: group
    provisioning:
    	strategy: create
        deferred: false
    dna:
    	path: '..path/to/dna'
        properties: ~
        network_seed: ~
        version: ~
        clone_limit: ....
    coordinators:
      zomes:
       - name: group
         path: ../../../target/wasm32-unknown-unknown/release/group_coordinator.wasm
         hash: uASDFJCaskldfjsdkalfj
         dependencies:
           - name: group_integrity
```

As part of refinement, I'd like to discuss whether `roles` should be renamed. I don't think it clearly communicates "a unit of an app". I believe we discussed this during the design calls but didn't come up with a better name yet.

I'd like to encourage and tidy up of naming or type structuring during this change. This is a pretty major change already and we're breaking the manifest format, so we should try to leave it in a good state that doesn't need updating again in the next versions of Holochain - as much as we can see that far ahead.
