### ISSUE TITLE
[BUG/Question] "get_links response channel dropped: likely response timeout"

### ISSUE THREAD

**Issue by zippy** [holochain/holochain#4944]
[Moss_0.14.0-rc.1_logs_1745504596517.zip](https://github.com/user-attachments/files/19894239/Moss_0.14.0-rc.1_logs_1745504596517.zip)

**Describe the bug**
In testing 0.5 in Moss we've started getting a new error response back from zome calls across a number of apps. 
`get_links response channel dropped: likely response timeout`

This starts coming back in large numbers, so this indicates a possible bug in clearly a connection that's no longer valid, but also as a new error, the question is how should app devs respond to handling this situation?

**Expected behavior**

**System information:**
- Moss 0.14.0-rc.1
- Holochain 0.5.0
- HDK 0.5, HDI 0.6

**Additional context**
logs attached. 

networkStats dump:

```
{
  "backend": "BackendLibDataChannel",
  "peer_urls": [
    "wss://dev-test-bootstrap2.holochain.org:443/7MGsC9-LFMbU2Hjy4tRlN3vFE1lVA9UwyluTiYy2lyM"
  ],
  "connections": [
    {
      "pub_key": "s_cc_yqwSKK0iUjCgRqkk9BnAbkKmpOVxSFsmMWncfk",
      "send_message_count": 1689,
      "send_bytes": 5243399,
      "recv_message_count": 1395,
      "recv_bytes": 586791,
      "opened_at_s": 1745344040,
      "is_webrtc": false
    },
    {
      "pub_key": "qjJVgeildhpKtpEfe-xJDdeJVWCRvoLH5ID9hd7TO-4",
      "send_message_count": 1678,
      "send_bytes": 4029929,
      "recv_message_count": 1613,
      "recv_bytes": 1556021,
      "opened_at_s": 1745344100,
      "is_webrtc": false
    }
  ]
}
```

**Comment by ThetaSinner** [comment]
The logs appear to be configured for `warn` but not `info`. We can see the symptoms from that but it's going to be difficult to figure out the cause. Can this be reproduced with logs configured for `info`?

Connections not going over WebRTC is unexpected. Could the `conductor-config.yaml` that's in use also be attached?

**Comment by zippy** [comment]
conductor config:


```
eric@zappy:~/.config/org.lightningrodlabs.moss-0.14/0.14.0-rc/default/data/conductor$ more conductor-config.yaml 
---
tracing_override: ~
data_root_path: /home/eric/.config/org.lightningrodlabs.moss-0.14/0.14.0-rc/default/data/conductor
device_seed_lair_tag: ~
danger_generate_throwaway_device_seed: false
keystore:
  type: lair_server
  connection_url: "unix:///tmp/lair.O8gujlBQpvOEX/socket?k=4_sXaiOl8W9S1BG7iavnwlewxjRqP3h_WFYyqeciAiY"
dpki:
  dna_path: ~
  network_seed: ""
  allow_throwaway_random_dpki_agent_key: false
  no_dpki: true
admin_interfaces:
  - driver:
      type: websocket
      port: 45659
      allowed_origins: "moss://admin.main,moss://admin.renderer"
network:
  bootstrap_url: "https://dev-test-bootstrap2.holochain.org/"
  signal_url: "wss://dev-test-bootstrap2.holochain.org/"
  webrtc_config:
    iceServers:
      - urls:
          - "stun:stun-0.main.infra.holo.host:443"
      - urls:
          - "stun:stun-1.main.infra.holo.host:443"
  target_arc_factor: 1
  advanced: ~
db_sync_strategy: Resilient
```
