### ISSUE TITLE
Implement zome config properties namespaced to the local zome

### ISSUE THREAD

**Issue by pospi** [holochain/holochain#909]
As a rule, I'm finding that most of the configuration I need to do in a multi-zome app is specific to each zome.

Currently, `dna_info()?.properties` and `zome_info()?.properties` return the same object- the props defined at the root of a `dna.yaml` file.

This affects code flexibility:

- Any configuration specific to a zome needs to be declared in the same top-level DNA property namespace as every other zome; and the only way for a zome to know where to look for properties is via hard-coding (chicken and egg problem). This will lead to name collisions and unofficial name registries for zomes to organise in the DNA-global namespace (probably documented in adjacent channels like Markdown files).
- Since `zome_info().properties` comes in as a raw `SerializedBytes`, it means that the details of the entire structure need to be known in order to decode it and read into sub-property attributes relevant to each independent zome.

Thus, the current situation forces a global namespace and hardcoding in zome crates.

**Proposal:** (breaking) change `zome_info()?.properties` to return a structure defined underneath that zome in `dna.yaml`.

```yaml
manifest_version: "1"
name: "my_dna"
uuid: ""
properties:
  dna_global: properties
    still: [defined, here]
zomes:
  - name: my_zome
    bundled: "./target/wasm32-unknown-unknown/release/my_zome.wasm"
    properties:
      zome_local: properties
        can: collide
  - name: my_other_zome
    bundled: "./target/wasm32-unknown-unknown/release/my_other_zome.wasm"
    properties:
      zome_local: properties
        are: independent
```
